### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by tranzmatt** [AlexNaga/rpi-people-counter#2]
At the risk of asking a stupid question, how to you install/run this?  I see pipenv files, but don't know how to actually run this.

**Comment by xam-ps** [comment]
Yea, in general a setup documentation would be pretty nice/handy.

**Comment by AlexNaga** [comment]
Yes totally agree, that part is missing! There are a lot of manual steps which I haven't got around to writing up.

Moving forward perhaps docker would be the way to go.

**Comment by mrkskwsnck** [comment]
Hi @AlexNaga, I stumbled over your project while on a research adventure. I'd like to use your project for my thesis, also. So I won't need to reinvent the wheel…

So far I successfully installed all dependencies. In the next step I will try to dig my way through the code, to get it running. Upon success I will provide a setup documentation.

**Comment by AlexNaga** [comment]
Hello,

What are you investing in your thesis? 

Since I have started a rewrite of this code to only include the scanning part. (removing support for multiple scanners).

**Comment by mrkskwsnck** [comment]
Well, my goal is to visualize the PAX count (as I say for **P**eople **A**ppro**X**imatelly :-) over a building floor plan (Open Street Map) for different use cases (e.g. emergency evacuation assistance system and such). Therefore I need a good basis for the PAX counter.

**Comment by AlexNaga** [comment]
Very interesting!

I've written a thesis of a similar topic which you may find of some value:
http://www.diva-portal.se/smash/get/diva2:1335277/FULLTEXT01.pdf

I would however recommend you not to try and get the current state of this
project up and running since it will be very time consuming. There are a
lot of redundant code.

This mean that you're better off inventing the wheel again since right now
the wheel isn't even round. I
 could upload the rewrite to a branch if you're interested to continue
coding since it's not yet done.

**Comment by mrkskwsnck** [comment]
In fact, I found your GitHub repository from exactly that document of yours :-)
Of course, I would like to have a look in your code rewrite.

**Comment by mrkskwsnck** [comment]
As I said I'm trying to write down the setup instructions. Until now I got this far, see: https://github.com/mrkskwsnck/rpi-people-counter/blob/missing_setup_instructions/README.md

But now I'm stuck with the scanner. After starting it up it says:

```
$ pipenv run python main.py
Error: Could not access WiFi adapter.
expected str, bytes or os.PathLike object, not NoneType
[========                                          ] 17%   4min 34s leftTraceback (most recent call last):
  File "main.py", line 70, in <module>
    main()
  File "main.py", line 53, in main
    wifi_devices_count = data[1]
IndexError: list index out of range
```

I also tried it running via `sudo` as I thought it might have something to do with permissions for accessing the monitoring interface `wlan0mon`.

Any suggestions would be appreciated <3

**Comment by AlexNaga** [comment]
So I used Kali for RPI that comes with nexmon included, if I remember
correctly.

Here's some post install steps that I had written down.


1.1 Configure the RPI
# kalipi-config

1.2 Change root password
1.3 Change timezone and keyboard layout


2. Generate new SSH keys
# dpkg-reconfigure openssh-server


3. Update the software
# apt update && apt upgrade


4. Install additional tools (the wireless metapackage)
# apt install kali-linux-wireless


5.1 Install Avahi
# apt install avahi-daemon

5.2 Enable Avahi
Avahi daemon can be enabled to start automatically in the system start
with the systemctl command below.
# systemctl enable avahi-daemon


6. Restart
$ reboot


7. Auto login SSH
Enter the command on local machine:
$ ssh-copy-id root@rpi-counter.local


8. Install pipenv
# pip install pipenv


9. Enable MongoDB
$ systemctl enable mongod.service


10.1 Install MQTT Broker (Mosquitto)
# apt install software-properties-common python-software-properties
# apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
# apt-get update
# apt install mosquitto

10.2 Start Mosquitto
# service mosquitto start


11. Install Redis
# apt install redis-server


12. Install piwheelshttps://www.piwheels.org



13. Install Node and NPM
$ wget -O - https://raw.githubusercontent.com/sdesalas/node-pi-zero/master/install-node-v.lts.sh
| bash


14. Install Uncomplicated Firewall (ufw)
# apt install ufw
$ ufw enable


All commands starting with $ are run as normal user.
All commands starting with # are to be run as root user (superuser).

**Comment by AlexNaga** [comment]
> As I said I'm trying to write down the setup instructions. Until now I got this far, see: https://github.com/mrkskwsnck/rpi-people-counter/blob/missing_setup_instructions/README.md
> 
> But now I'm stuck with the scanner. After starting it up it says:
> 
> ```
> $ pipenv run python main.py
> Error: Could not access WiFi adapter.
> expected str, bytes or os.PathLike object, not NoneType
> [========                                          ] 17%   4min 34s leftTraceback (most recent call last):
>   File "main.py", line 70, in <module>
>     main()
>   File "main.py", line 53, in main
>     wifi_devices_count = data[1]
> IndexError: list index out of range
> ```
> 
> I also tried it running via `sudo` as I thought it might have something to do with permissions for accessing the monitoring interface `wlan0mon`.
> 
> Any suggestions would be appreciated <3

So I used Kali for RPI that comes with nexmon included, if I remember
correctly.

The script I used to start monitor mode was:
```  
#!/bin/bash

# To check for interfaces: iwconfig

INTERFACE="wlan0"

# Start monitor mode
sudo airmon-ng start $INTERFACE

# Restart DHCP service for WiFi interface
sudo dhclient $INTERFACE
```

Here's some post install steps that I had written down. Some of them might not be valid for the current code.


```
1.1 Configure the RPI
# kalipi-config

1.2 Change root password
1.3 Change timezone and keyboard layout


2. Generate new SSH keys
# dpkg-reconfigure openssh-server


3. Update the software
# apt update && apt upgrade


4. Install additional tools (the wireless metapackage)
# apt install kali-linux-wireless


5.1 Install Avahi
# apt install avahi-daemon

5.2 Enable Avahi
Avahi daemon can be enabled to start automatically in the system start
with the systemctl command below.
# systemctl enable avahi-daemon


6. Restart
$ reboot


7. Auto login SSH
Enter the command on local machine:
$ ssh-copy-id root@rpi-counter.local


8. Install pipenv
# pip install pipenv


9. Enable MongoDB
$ systemctl enable mongod.service


10.1 Install MQTT Broker (Mosquitto)
# apt install software-properties-common python-software-properties
# apt-add-repository ppa:mosquitto-dev/mosquitto-ppa
# apt-get update
# apt install mosquitto

10.2 Start Mosquitto
# service mosquitto start


11. Install Redis
# apt install redis-server


12. Install piwheels - redundant?
See: https://www.piwheels.org



13. Install Node and NPM
$ wget -O - https://raw.githubusercontent.com/sdesalas/node-pi-zero/master/install-node-v.lts.sh
| bash


14. Install Uncomplicated Firewall (ufw)
# apt install ufw
$ ufw enable
```


All commands starting with $ are run as normal user.
All commands starting with # are to be run as root user (superuser).

**Comment by mrkskwsnck** [comment]
I created a pull request with my setup instructions based on Raspbian. So far it seems to work well. Despite the fact, that on Raspbian you need to compile WiFi driver/firmware by yourself, in order to make scanning in monitor mode possible. In hindsight I would everyone else recommend to use Kali Linux in the first place, as it is also based on Debian.

As you recommended, I decided to look for a different (simpler) approach to scan for wireless devices for my project. However, your project helped me a lot to understand how to build a scanning device.

**Comment by AlexNaga** [comment]
Yeah I won't be able to upload the rewrite of the code until next week.

You can email me if you have anything you want to discuss regarding scanners :)

**Comment by AlexNaga** [comment]
Closing due to the installation process added to the readme.
